<h2>Roll No : CO2032 Name : Nishagiri Dattatray Kamble</h2>

<h1>NumPy</h1>

<h3>~version checkig</h3>

In [3]:
import numpy as np

print(np.__version__)
print(np.version.version)

1.26.4
1.26.4


<h3>1. create a 1-D array of numbers 1 to 20</h3>

In [5]:
import numpy as np
arr = np.arange(1,21)             #arange(start, stop)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


<h3>2. Create a 5*5 array with all zeros</h3>

In [6]:
import numpy as np


arr = np.zeros((5, 5), dtype=int)          ## Create a 5x5 array of zeros

print("5x5 Array of Zeros:")
print(arr)

5x5 Array of Zeros:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


<h3>3. Create 4*4 indentity matrix</h3>

In [10]:
arr = np.array(((1,2,3,4), (5,6,7,8), (1,3,4,2), (3,5,6,4)))
print(arr)
print(arr.ndim)


[[1 2 3 4]
 [5 6 7 8]
 [1 3 4 2]
 [3 5 6 4]]
2


In [11]:
import numpy as np


arr = np.eye(4, dtype=int)             ## Create a 4x4 identity matrix

print("4x4 Identity Matrix:")
print(arr)

4x4 Identity Matrix:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


<h3>4. Create an array of 10 evenly spaced numbers between 0 and 1</h3>

In [1]:
import numpy as np

arr = np.linspace(0, 1, 10)


print("Array:")
print(arr)

Array:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


<h3>5. Reverse a given 1-D array</h3>

In [2]:
import numpy as np

                                                  # Create a 1-D array
arr = np.array([10, 20, 30, 40, 50])

                                                  # Reverse the array
reverse_arr = arr[::-1]


print("Original Array:", arr)
print("Reversed Array:", reverse_arr)

Original Array: [10 20 30 40 50]
Reversed Array: [50 40 30 20 10]


<h3>6. Find the shape, size, and dtype of a given array</h3>

In [3]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])


print("Array:")
print(arr)

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int32


<h3>7. Replace all odd numbers in an array with -1</h3>

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1

print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


<h3>8. Find the sum, mean, and max of an array</h3>

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))

Sum: 150
Mean: 30.0
Maximum: 50


<h3>9. Create a 3×3 array of random integers between 1 and 100.</h3>

In [6]:
import numpy as np

arr = np.random.randint(1, 101, (3, 3))

print(arr)

[[56 18 16]
 [19  6  8]
 [81 87 39]]


<h3>10. Stack two 1-D arrays vertically and horizontally</h3>

In [7]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Vertical Stack:")
print(np.vstack((arr1, arr2)))

print("Horizontal Stack:")
print(np.hstack((arr1, arr2)))

Vertical Stack:
[[1 2 3]
 [4 5 6]]
Horizontal Stack:
[1 2 3 4 5 6]


<h3>11. Extract every 3rd element from an array.</h3>

In [8]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80,90])

result = arr[::3]

print(result)

[10 40 70]


<h3>Q12. Find common elements between two arrays.</h3>

In [9]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,5,6,7,8])

common = np.intersect1d(arr1, arr2)

print(common)

[4 5]


<h3>Q13. Convert a list of temperatures in Celsius to Fahrenheit using vectorized math.</h3>

In [10]:
import numpy as np

celsius = np.array([0, 20, 30, 40])         #F = (C × 9/5) + 32

fahrenheit = (celsius * 9/5) + 32

print(fahrenheit)

[ 32.  68.  86. 104.]


<h3>Q14. Count the number of even numbers in an array.</h3>

In [11]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])

count = np.sum(arr % 2 == 0)

print("Even Numbers:", count)

Even Numbers: 5


<h3>Q15. Create an array and compute its transpose.</h3>

In [12]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6]])

transpose = arr.T

print("Original Array:")
print(arr)

print("Transpose:")
print(transpose)

Original Array:
[[1 2 3]
 [4 5 6]]
Transpose:
[[1 4]
 [2 5]
 [3 6]]


<h2>~Creating Arrays</h2>

In [19]:
import numpy as np

arr = np.array([10, 20, 30, 40])                  #Creates a NumPy array from a Python list or tuple

print(arr)

[10 20 30 40]


In [20]:
import numpy as np

arr = np.arange(1, 11)                         #Creates an array with values in a specified range

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
import numpy as np

arr = np.linspace(0, 1, 5)                       #reates evenly spaced numbers between two values.

print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [22]:
import numpy as np

arr = np.zeros((2,3), dtype=int)              #Creates an array filled with zeros

print(arr)

[[0 0 0]
 [0 0 0]]


In [23]:
import numpy as np

arr = np.ones((2,3), dtype=int)                        #Creates an array filled with ones.

print(arr)

[[1 1 1]
 [1 1 1]]


In [24]:
import numpy as np

arr = np.eye(3, dtype=int)           #Creates an identity matrix

print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [25]:
import numpy as np

arr = np.random.randint(1, 10, (2,3))                 #Generates random integers.

print(arr)

[[6 5 8]
 [6 8 7]]


In [26]:
import numpy as np

arr = np.random.rand(2,3)                 #Generates random decimal numbers between 0 and 1.

print(arr)

[[0.15035603 0.84131727 0.61713416]
 [0.38623589 0.44918166 0.61133552]]


<h2>~Inspecting Arrays</h2>

In [27]:
import numpy as np

arr = np.array([[1,2],[3,4]])                #Returns the number of dimensions.

print(arr.ndim)

2


In [28]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])                         #Returns the shape of the array.

print(arr.shape)

(2, 3)


In [29]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])           #Returns the total number of elements.

print(arr.size)

6


In [30]:
import numpy as np

arr = np.array([10,20,30])               #Returns the data type of the array.

print(arr.dtype)

int32


In [31]:
import numpy as np

arr = np.array([10,20,30])               #Returns the memory size of one element.

print(arr.itemsize)

4


<h2>Indexing & Slicing</h2>

In [32]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])            #Access a single element using its index.

print(arr[2])

30


In [33]:
import numpy as np

arr = np.array([[10,20,30],                   #Access an element from a 2-D array using row and column index.
                [40,50,60]])

print(arr[1,2])

60


In [34]:
import numpy as np

arr = np.array([10,20,30,40,50,60])             #Extract a portion of an array.

print(arr[1:5:2])

[20 40]


In [35]:
import numpy as np

arr = np.array([10,20,30,40,50])            #Access multiple elements using a list of indices.

print(arr[[0,2,4]])

[10 30 50]


In [36]:
import numpy as np

arr = np.array([2,5,7,9,3,8])       #Select elements that satisfy a condition.

print(arr[arr > 5])

[7 9 8]


In [37]:
import numpy as np

arr = np.array([2,5,7,9,10,12])

print(arr[(arr > 5) & (arr < 10)])                 #Apply multiple conditions using &.

[7 9]


<h2>~Mutating Arrays</h2>

In [38]:
import numpy as np

arr = np.array([10,20,30])

arr[1] = 100

print(arr)                   #Replace an element at a specific index.

[ 10 100  30]


In [39]:
import numpy as np

arr = np.array([10,20,30])                   #Adds new elements and returns a new array.

new_arr = np.append(arr, 40)

print(new_arr)

[10 20 30 40]


In [40]:
import numpy as np

arr = np.array([10,20,30,40])
                                                #Removes an element from an array.
new_arr = np.delete(arr, 1)

print(new_arr)

[10 30 40]


In [41]:
import numpy as np

arr = np.array([50,20,40,10,30])                    #Sorts the array in ascending order.

sorted_arr = np.sort(arr)

print(sorted_arr)

[10 20 30 40 50]


In [42]:
import numpy as np

arr = np.array([50,20,40,10,30])            #Sorts the original array in place.

arr.sort()

print(arr)

[10 20 30 40 50]


In [43]:
import numpy as np

arr = np.array([50,20,40,10,30])                  #Returns the indices that would sort the array.

print(np.argsort(arr))

[3 1 4 2 0]


<h2>~Copy vs View</h2>

In [44]:
import numpy as np

a = np.array([10, 20, 30])

b = a
b[0] = 100

print("a:", a)
print("b:", b)

a: [100  20  30]
b: [100  20  30]


In [45]:
import numpy as np

a = np.array([10,20,30,40,50])

b = a[1:4]

b[0] = 100

print("a:", a)
print("b:", b)

a: [ 10 100  30  40  50]
b: [100  30  40]


In [46]:
import numpy as np

a = np.array([10,20,30,40,50])

b = a[[1,3]]

b[0] = 100

print("a:", a)
print("b:", b)

a: [10 20 30 40 50]
b: [100  40]


In [47]:
import numpy as np

a = np.array([-2,5,-4,8])

b = a[a > 0]

b[0] = 100

print("a:", a)
print("b:", b)

a: [-2  5 -4  8]
b: [100   8]


In [48]:
import numpy as np

a = np.array([1,2,3])

b = a.copy()

b[0] = 100

print("a:", a)
print("b:", b)

a: [1 2 3]
b: [100   2   3]


In [49]:
import numpy as np

a = np.array([10,20,30,40])

b = a[1:3]

print(np.shares_memory(a, b))

True


<h2>~Reshaping</h2>

In [51]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])                 #Changes the shape of an array without changing its data.

b = a.reshape(2, 3)

print(b)

[[1 2 3]
 [4 5 6]]


In [52]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])             #Converts a multi-dimensional array into a 1-D copy.

b = a.flatten()

print(b)

[1 2 3 4 5 6]


In [53]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])                 #Converts a multi-dimensional array into a 1-D view whenever possible.

b = a.ravel()

print(b)

[1 2 3 4 5 6]


In [54]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])                      #Returns the transpose of an array (rows become columns).

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [55]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])                  #Returns the transpose of an array.

b = a.transpose()

print(b)

[[1 4]
 [2 5]
 [3 6]]


<h2>~Math & Ufuncs</h2>

In [56]:
import numpy as np

a = np.array([1,2,3])                          #Adds corresponding elements of two arrays.
b = np.array([4,5,6])

print(a + b)

[5 7 9]


In [57]:
import numpy as np
                                     #Subtracts corresponding elements.
a = np.array([10,20,30])
b = np.array([1,2,3])

print(a - b)

[ 9 18 27]


In [58]:
import numpy as np

a = np.array([2,3,4])
b = np.array([5,6,7])                              #Performs element-wise multiplication.

print(a * b)

[10 18 28]


In [59]:
import numpy as np

a = np.array([10,20,30])                           #Performs element-wise division.
b = np.array([2,4,5])

print(a / b)

[5. 5. 6.]


In [60]:
import numpy as np

a = np.array([[1,2],                                   #Performs matrix multiplication.
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print(a @ b)

[[19 22]
 [43 50]]


In [61]:
import numpy as np

a = np.array([4,9,16,25])                       #Finds the square root of each element.

print(np.sqrt(a))

[2. 3. 4. 5.]


In [63]:
import numpy as np

a = np.array([1,2,3])                #Calculates e^x  for each element.

print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692]


In [64]:
import numpy as np
                                           #Calculates the natural logarithm.
a = np.array([1,2,4])

print(np.log(a))

[0.         0.69314718 1.38629436]


In [65]:
import numpy as np
 
a = np.array([0, np.pi/2, np.pi])                               #Calculates the sine of each element 

print(np.sin(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [66]:
import numpy as np

a = np.array([2,8,5])
b = np.array([3,6,7])                         #Returns the larger value from two arrays.

print(np.maximum(a,b))

[3 8 7]


In [67]:
import numpy as np

a = np.array([2,8,5])                      #Returns the smaller value from two arrays.
b = np.array([3,6,7])

print(np.minimum(a,b))

[2 6 5]


In [68]:
import numpy as np

a = np.array([2.3456, 4.5678, 8.9123])                  #Rounds decimal values.

print(np.around(a, 2))

[2.35 4.57 8.91]


<h2>~Aggregation</h2>

In [69]:
import numpy as np

a = np.array([10,20,30])               #Returns the sum of all elements.

print(np.sum(a))

60


In [70]:
import numpy as np

a = np.array([10,20,30])                
a = np.array([10,20,30])                #Returns the average value.

print(np.mean(a))

20.0


In [71]:
import numpy as np

a = np.array([10,20,30,40,50])              #Returns the middle value.

print(np.median(a))

30.0


In [72]:
import numpy as np

a = np.array([2,4,6,8])                           #Returns the standard deviation.

print(np.std(a))

2.23606797749979


In [73]:
import numpy as np

a = np.array([2,4,6,8])                  #Returns the variance.

print(np.var(a))

5.0


In [74]:
import numpy as np

a = np.array([5,9,2,8])                      #Returns the smallest element.

print(np.min(a))

2


In [75]:
import numpy as np

a = np.array([5,9,2,8])                     #Returns the largest element.

print(np.max(a))

9


In [76]:
import numpy as np

a = np.array([5,9,2,8])                   #Returns the index of the smallest element.

print(np.argmin(a))

2


In [77]:
import numpy as np

a = np.array([5,9,2,8])                        #Returns the index of the largest element.

print(np.argmax(a))

1


<h2>Axis in NumPy</h2>

In [78]:
import numpy as np

a = np.array([[1,2,3],                                      #Performs the operation column-wise by collapsing the rows.
              [4,5,6]])

print(np.sum(a, axis=0))

[5 7 9]


In [79]:
import numpy as np

a = np.array([[1,2,3],                                  #Performs the operation row-wise by collapsing the columns.
              [4,5,6]])

print(np.sum(a, axis=1))

[ 6 15]


<h2>Stacking & Splitting</h2>

In [80]:
import numpy as np

a = np.array([1,2,3])                                  #Stacks arrays vertically (row-wise).
b = np.array([4,5,6])

print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [81]:
import numpy as np

a = np.array([1,2,3])                      #Stacks arrays horizontally (column-wise).
b = np.array([4,5,6])

print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [82]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])                          #Stacks arrays along a new axis.

print(np.stack((a,b), axis=0))

[[1 2 3]
 [4 5 6]]


In [83]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])                               #Joins two or more arrays along an existing axis.

print(np.concatenate((a,b), axis=0))

[1 2 3 4 5 6]


In [84]:
import numpy as np

a = np.array([10,20,30,40])                           #Splits an array into equal parts.

print(np.split(a,2))

[array([10, 20]), array([30, 40])]


In [85]:
import numpy as np

a = np.array([[1,2],
              [3,4]])                                #Splits an array vertically (row-wise).

print(np.vsplit(a,2))

[array([[1, 2]]), array([[3, 4]])]


In [86]:
import numpy as np

a = np.array([[1,2],                                       #Splits an array horizontally (column-wise).
              [3,4]])

print(np.hsplit(a,2))

[array([[1],
       [3]]), array([[2],
       [4]])]


<h2>~Linear Algebra (np.linalg)</h2>

In [88]:
import numpy as np

A = np.array([[2, 3],                     #Finds the determinant of a square matrix.
              [1, 4]])

print(np.linalg.det(A))

5.000000000000001


In [89]:
import numpy as np

A = np.array([[1, 2],                                  #Finds the inverse of a square matrix.
              [3, 4]])

print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [90]:
import numpy as np

A = np.array([[2, 1],                                    #Solves the matrix equation Ax = b.
              [1, 3]])

b = np.array([8, 13])

x = np.linalg.solve(A, b)

print(x)

[2.2 3.6]


In [91]:
import numpy as np

A = np.array([[2, 0],
              [0, 3]])

values, vectors = np.linalg.eig(A)                            #import numpy as np

A = np.array([[2, 0],
              [0, 3]])

values, vectors = np.linalg.eig(A)

print("Eigenvalues:")
print(values)

print("Eigenvectors:")
print(vectors)



Eigenvalues:
[2. 3.]
Eigenvectors:
[[1. 0.]
 [0. 1.]]


In [92]:
import numpy as np

A = np.array([[1, 2],
              [2, 4]])

print(np.linalg.matrix_rank(A))                               #Returns the rank of a matrix.

1


<h2>Handling Missing Data</h2>

In [93]:
import numpy as np

a = np.array([10, 20, np.nan, 40])                                 #Represents a missing value.

print(a)

[10. 20. nan 40.]


In [94]:
import numpy as np

a = np.array([10, np.nan, 30])                             #Checks whether each element is NaN.

print(np.isnan(a))

[False  True False]


In [95]:
import numpy as np

a = np.array([10, 20, np.nan, 40])                          #Calculates the mean while ignoring NaN values.

print(np.nanmean(a))

23.333333333333332


In [96]:
import numpy as np

a = np.array([10, 20, np.nan, 40])                     #Calculates the sum while ignoring NaN values.

print(np.nansum(a))

70.0


In [42]:
import numpy as np

arr = np.array([50,20,40,10,30])            #Sorts the original array in place.

arr.sort()

print(arr)

[10 20 30 40 50]


In [43]:
import numpy as np

arr = np.array([50,20,40,10,30])                  #Returns the indices that would sort the array.

print(np.argsort(arr))

[3 1 4 2 0]


<h2>~Copy vs View</h2>

In [44]:
import numpy as np

a = np.array([10, 20, 30])

b = a
b[0] = 100

print("a:", a)
print("b:", b)

a: [100  20  30]
b: [100  20  30]


In [45]:
import numpy as np

a = np.array([10,20,30,40,50])

b = a[1:4]

b[0] = 100

print("a:", a)
print("b:", b)

a: [ 10 100  30  40  50]
b: [100  30  40]


In [46]:
import numpy as np

a = np.array([10,20,30,40,50])

b = a[[1,3]]

b[0] = 100

print("a:", a)
print("b:", b)

a: [10 20 30 40 50]
b: [100  40]


In [47]:
import numpy as np

a = np.array([-2,5,-4,8])

b = a[a > 0]

b[0] = 100

print("a:", a)
print("b:", b)

a: [-2  5 -4  8]
b: [100   8]


In [48]:
import numpy as np

a = np.array([1,2,3])

b = a.copy()

b[0] = 100

print("a:", a)
print("b:", b)

a: [1 2 3]
b: [100   2   3]


In [49]:
import numpy as np

a = np.array([10,20,30,40])

b = a[1:3]

print(np.shares_memory(a, b))

True


<h2>~Reshaping</h2>

In [51]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])                 #Changes the shape of an array without changing its data.

b = a.reshape(2, 3)

print(b)

[[1 2 3]
 [4 5 6]]


In [52]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])             #Converts a multi-dimensional array into a 1-D copy.

b = a.flatten()

print(b)

[1 2 3 4 5 6]


In [53]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])                 #Converts a multi-dimensional array into a 1-D view whenever possible.

b = a.ravel()

print(b)

[1 2 3 4 5 6]


In [54]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])                      #Returns the transpose of an array (rows become columns).

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [55]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])                  #Returns the transpose of an array.

b = a.transpose()

print(b)

[[1 4]
 [2 5]
 [3 6]]


<h2>~Math & Ufuncs</h2>

In [56]:
import numpy as np

a = np.array([1,2,3])                          #Adds corresponding elements of two arrays.
b = np.array([4,5,6])

print(a + b)

[5 7 9]


In [57]:
import numpy as np
                                     #Subtracts corresponding elements.
a = np.array([10,20,30])
b = np.array([1,2,3])

print(a - b)

[ 9 18 27]


In [58]:
import numpy as np

a = np.array([2,3,4])
b = np.array([5,6,7])                              #Performs element-wise multiplication.

print(a * b)

[10 18 28]


In [59]:
import numpy as np

a = np.array([10,20,30])                           #Performs element-wise division.
b = np.array([2,4,5])

print(a / b)

[5. 5. 6.]


In [60]:
import numpy as np

a = np.array([[1,2],                                   #Performs matrix multiplication.
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print(a @ b)

[[19 22]
 [43 50]]


In [61]:
import numpy as np

a = np.array([4,9,16,25])                       #Finds the square root of each element.

print(np.sqrt(a))

[2. 3. 4. 5.]


In [63]:
import numpy as np

a = np.array([1,2,3])                #Calculates e^x  for each element.

print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692]


In [64]:
import numpy as np
                                           #Calculates the natural logarithm.
a = np.array([1,2,4])

print(np.log(a))

[0.         0.69314718 1.38629436]


In [65]:
import numpy as np
 
a = np.array([0, np.pi/2, np.pi])                               #Calculates the sine of each element 

print(np.sin(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [66]:
import numpy as np

a = np.array([2,8,5])
b = np.array([3,6,7])                         #Returns the larger value from two arrays.

print(np.maximum(a,b))

[3 8 7]


In [67]:
import numpy as np

a = np.array([2,8,5])                      #Returns the smaller value from two arrays.
b = np.array([3,6,7])

print(np.minimum(a,b))

[2 6 5]


In [68]:
import numpy as np

a = np.array([2.3456, 4.5678, 8.9123])                  #Rounds decimal values.

print(np.around(a, 2))

[2.35 4.57 8.91]


<h2>~Aggregation</h2>

In [69]:
import numpy as np

a = np.array([10,20,30])               #Returns the sum of all elements.

print(np.sum(a))

60


In [70]:
import numpy as np

a = np.array([10,20,30])                
a = np.array([10,20,30])                #Returns the average value.

print(np.mean(a))

20.0


In [71]:
import numpy as np

a = np.array([10,20,30,40,50])              #Returns the middle value.

print(np.median(a))

30.0


In [72]:
import numpy as np

a = np.array([2,4,6,8])                           #Returns the standard deviation.

print(np.std(a))

2.23606797749979


In [73]:
import numpy as np

a = np.array([2,4,6,8])                  #Returns the variance.

print(np.var(a))

5.0


In [74]:
import numpy as np

a = np.array([5,9,2,8])                      #Returns the smallest element.

print(np.min(a))

2


In [75]:
import numpy as np

a = np.array([5,9,2,8])                     #Returns the largest element.

print(np.max(a))

9


In [76]:
import numpy as np

a = np.array([5,9,2,8])                   #Returns the index of the smallest element.

print(np.argmin(a))

2


In [77]:
import numpy as np

a = np.array([5,9,2,8])                        #Returns the index of the largest element.

print(np.argmax(a))

1


<h2>Axis in NumPy</h2>

In [78]:
import numpy as np

a = np.array([[1,2,3],                                      #Performs the operation column-wise by collapsing the rows.
              [4,5,6]])

print(np.sum(a, axis=0))

[5 7 9]


In [79]:
import numpy as np

a = np.array([[1,2,3],                                  #Performs the operation row-wise by collapsing the columns.
              [4,5,6]])

print(np.sum(a, axis=1))

[ 6 15]


<h2>Stacking & Splitting</h2>

In [80]:
import numpy as np

a = np.array([1,2,3])                                  #Stacks arrays vertically (row-wise).
b = np.array([4,5,6])

print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [81]:
import numpy as np

a = np.array([1,2,3])                      #Stacks arrays horizontally (column-wise).
b = np.array([4,5,6])

print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [82]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])                          #Stacks arrays along a new axis.

print(np.stack((a,b), axis=0))

[[1 2 3]
 [4 5 6]]


In [83]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])                               #Joins two or more arrays along an existing axis.

print(np.concatenate((a,b), axis=0))

[1 2 3 4 5 6]


In [84]:
import numpy as np

a = np.array([10,20,30,40])                           #Splits an array into equal parts.

print(np.split(a,2))

[array([10, 20]), array([30, 40])]


In [85]:
import numpy as np

a = np.array([[1,2],
              [3,4]])                                #Splits an array vertically (row-wise).

print(np.vsplit(a,2))

[array([[1, 2]]), array([[3, 4]])]


In [86]:
import numpy as np

a = np.array([[1,2],                                       #Splits an array horizontally (column-wise).
              [3,4]])

print(np.hsplit(a,2))

[array([[1],
       [3]]), array([[2],
       [4]])]


<h2>~Linear Algebra (np.linalg)</h2>

In [88]:
import numpy as np

A = np.array([[2, 3],                     #Finds the determinant of a square matrix.
              [1, 4]])

print(np.linalg.det(A))

5.000000000000001


In [89]:
import numpy as np

A = np.array([[1, 2],                                  #Finds the inverse of a square matrix.
              [3, 4]])

print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [90]:
import numpy as np

A = np.array([[2, 1],                                    #Solves the matrix equation Ax = b.
              [1, 3]])

b = np.array([8, 13])

x = np.linalg.solve(A, b)

print(x)

[2.2 3.6]


In [91]:
import numpy as np

A = np.array([[2, 0],
              [0, 3]])

values, vectors = np.linalg.eig(A)                            #import numpy as np

A = np.array([[2, 0],
              [0, 3]])

values, vectors = np.linalg.eig(A)

print("Eigenvalues:")
print(values)

print("Eigenvectors:")
print(vectors)



Eigenvalues:
[2. 3.]
Eigenvectors:
[[1. 0.]
 [0. 1.]]


In [92]:
import numpy as np

A = np.array([[1, 2],
              [2, 4]])

print(np.linalg.matrix_rank(A))                               #Returns the rank of a matrix.

1


<h2>Handling Missing Data</h2>

In [93]:
import numpy as np

a = np.array([10, 20, np.nan, 40])                                 #Represents a missing value.

print(a)

[10. 20. nan 40.]


In [94]:
import numpy as np

a = np.array([10, np.nan, 30])                             #Checks whether each element is NaN.

print(np.isnan(a))

[False  True False]


In [95]:
import numpy as np

a = np.array([10, 20, np.nan, 40])                          #Calculates the mean while ignoring NaN values.

print(np.nanmean(a))

23.333333333333332


In [96]:
import numpy as np

a = np.array([10, 20, np.nan, 40])                     #Calculates the sum while ignoring NaN values.

print(np.nansum(a))

70.0
